services:
  routecal:
    build: .
    container_name: routecal
    ports:
      - "54891:5000"
    environment:
      - NAVER_CLIENT_ID
      - NAVER_CLIENT_SECRET
    volumes:
      - /home/ubuntu/routecal:/app/data
    networks:
      - portainer_portainer-net
    restart: unless-stopped
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
