version: '3.8'

services:
  routecal:
    image: python:3.10-slim
    container_name: routecal
    ports:
      - "54891:5000"
    environment:
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
    volumes:
      - /home/ubuntu/routecal/app:/app
      - /home/ubuntu/routecal/results:/app/results
    working_dir: /app
    command: python app.py
    networks:
      - portainer_portainer-net
    restart: unless-stopped

networks:
  portainer_portainer-net:
    external: true
